-- MySQL Script generated by MySQL Workbench
-- Tue Jun 22 16:40:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Eco-merceDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Eco-merceDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Eco-merceDB` DEFAULT CHARACTER SET utf8 ;
USE `Eco-merceDB` ;

-- -----------------------------------------------------
-- Table `Eco-merceDB`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Eco-merceDB`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `e-mail` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `endereco` LONGBLOB NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `CNPJ` VARCHAR(14) NOT NULL,
  `usuario_tipo` INT(3) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `e-mail_UNIQUE` (`e-mail` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE,
  UNIQUE INDEX `usuario_tipo_UNIQUE` (`usuario_tipo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Eco-merceDB`.`voucher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Eco-merceDB`.`voucher` (
  `id_voucher` INT NOT NULL AUTO_INCREMENT,
  `empresa_parceira` VARCHAR(45) NOT NULL,
  `desconto_aplicado` FLOAT NOT NULL,
  `descricao_voucher` TEXT(70000) NOT NULL,
  `produto` BLOB NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_voucher`, `usuario_id_usuario`),
  INDEX `fk_produto_usuario_idx` (`usuario_id_usuario` ASC) VISIBLE,
  UNIQUE INDEX `produto_UNIQUE` (`produto` ASC) VISIBLE,
  CONSTRAINT `fk_produto_usuario`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `Eco-merceDB`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
